# server.port 就是我们在 yml 配置文件里面定义的属性，我们可以自定义任意属性名，通过 @Value 注解就可以将其取出来。
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://192.168.5.241:3306/hanif?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: dashu0701
    driver-class-name: com.mysql.jdbc.Driver

# 假设一个需求是这样的：项目要求使用阿里云的 OSS 进行文件上传。我们知道，一个项目一般会分为开发环境、测试环境和生产环境。
# OSS 文件上传一般有如下几个参数：appKey、appSecret、bucket、endpoint 等。不同环境的参数都可能不一样，这样便于区分。
appKey: 1
appSecret: 1
bucket: 1
endPoint: https://www.aliyun.com
